### ISSUE TITLE
Make Honeygrove usable without Broker

### ISSUE THREAD

**Issue by AdrianMiska** [UHH-ISS/honeygrove#2]
Currently Honeygrove doesn't work when started without having Broker installed and working. Broker doesn't run on Windows and macOS though and is generally not very easy to get working. 

Making our code less dependent on Broker would be great for portability and stability.

**Comment by jfrangop** [comment]
would it be sufficient to add an option to not use broker or did you thought about an other way to communicate with the management-console and the EKStack? The former would be solvable through conditionally include broker and sending messages via it, but then only the output of the honeypot would be usable.

**Comment by AdrianMiska** [comment]
Yes, I'm thinking of a simple option in the config file to just ignore broker altogether. The honeypot would still produce log files to evaluate. An alternative way of communication could be developed later on but that's no priority.
