### ISSUE TITLE
Can't start honeygrove

### ISSUE THREAD

**Issue by vikasjayaswal** [UHH-ISS/honeygrove#32]
I have followed the instructions, but can't seem to start the program.

$ sudo python3 -m honeygrove

root@6d3fe07e581d:/honeygrove/honeygrove# python3 -m honeygrove
/usr/bin/python3: No module named honeygrove

There doesn't seem to be a honeygrove module?

**Comment by iBigQ** [comment]
Try to execute this command from the top level directory in this repository. In your case "/honeygrove/".
